name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install bandit pip-audit semgrep

    - name: Run Bandit security scan
      run: |
        echo "Running Bandit security scan..."
        bandit -r app/ -f json -o bandit-report.json || true
        bandit -r app/ -ll

    - name: Run pip-audit vulnerability scan
      run: |
        echo "Running pip-audit vulnerability scan..."
        pip-audit -r requirements/requirements.txt --format=json --output=pip-audit-report.json || true
        pip-audit -r requirements/requirements.txt || true

    - name: Run Semgrep security scan
      run: |
        echo "Running Semgrep security scan..."
        semgrep --config=auto app/ --json --output=semgrep-report.json || true
        semgrep --config=auto app/

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports-${{ github.run_number }}
        path: |
          bandit-report.json
          pip-audit-report.json
          semgrep-report.json

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC
